# Generated by Django 5.1.7 on 2025-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrationkey',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registrationkey',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registrationkey',
            name='number_of_farmers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationkey',
            name='for_role',
            field=models.CharField(choices=[('cooperative', 'Cooperative'), ('farmer', 'Farmer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cooperative', 'Cooperative'), ('farmer', 'Farmer')], max_length=20),
        ),
    ]
