# Generated by Django 5.1.7 on 2025-05-18 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationkey_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
