# Generated by Django 5.1.7 on 2025-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registrationkey_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
