# Generated by Django 5.1.7 on 2025-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_address_user_number_of_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_services',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
