# Generated by Django 5.1.7 on 2025-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_active_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationkey',
            name='for_role',
            field=models.CharField(choices=[('cooperative', 'Cooperative'), ('farmer', 'Farmer'), ('reset_password', 'Reset Password')], max_length=20),
        ),
    ]
