import React, { createContext, useState, useEffect } from "react";

// Complete translations for all languages
const translations = {
    en: {
        common: {
            welcome: "Welcome",
            memberOf: "Member of",
            activeServices: "Active Services",
            provideFeedback: "Provide Feedback",
            viewDetails: "View Details",
            signUp: "Sign Up",
            login: "Login",
            logout: "Logout",
            joined: "Joined",
            active: "Active",
            at: "at",
            posted: "Posted",
            home: "Home",
            about: "About",
            contact: "Contact",
            Phone_Number: "Phone Number",
            username: "Username",
            password: "Password",
            rememberMe: "Remember me",
            forgotPassword: "Forgot password?",
            signingIn: "Signing in...",
            signIn: "Sign in",
            noAccount: "Don't have an account?",
            loginSuccess: "Login successful! Redirecting...",
            loginFailed: "Login failed. Please check your credentials and try again.",
        },
        farmer: {
            homeTitle: "Farmer Dashboard",
            feedbackTitle: "Provide Service Feedback",
            noServicesFound: "No active services found",
            noServicesDescription: "You don't have any active services at the moment",
            exploreServices: "Explore Services",
            yourActiveServices: "Your Active Services",
            cooperativeAnnouncement: "Cooperative Announcement",
            upcomingMeeting: "Upcoming Meeting",
            meetingDetails: "The next cooperative meeting will be on",
            meetingLocation: "at the cooperative office",
            leadershipDiscussion: "leadership will discuss new farming techniques",
            loginSubtitle: "Sign in to manage your farm activities",
            phonePlaceholder: "Enter your phone number",
            phoneValidation: "Please enter a 10-digit phone number",
            passwordPlaceholder: "Enter your password",
            createAccount: "Create new farmer account",
        },
        admin: {
            homeTitle: "Admin Dashboard",
            loginSubtitle: "Sign in to use the platform",
            usernamePlaceholder: "Enter your username",
            passwordPlaceholder: "Enter your password",
            joinAsCoop: "Join as a Cooperative",
        },
        cooperative: {
            homeTitle: "Cooperative Dashboard",
            addFarmer: "Add New Farmer",
            location: "Location",
            locationNotSpecified: "Location not specified",
            cooperative: "Cooperative",
            totalFarmers: "Total Farmers",
            activeUsers: "Active Users",
            farmers: "farmers",
            noDescription: "No description available",
            serviceID: "Service ID",
        },
        feedback: {
            noServiceSelected: "No Service Selected",
            noServiceDescription: "Please go back and select a service to provide feedback.",
            feedbackFor: "Feedback for",
            returnToServices: "Return to Services",
            checkingEligibility: "Checking feedback eligibility...",
            couldNotVerify: "Could not verify feedback eligibility.",
            submitSuccess: "Feedback submitted successfully!",
            submitFailed: "Failed to submit feedback.",
            specificService: "Specific Service",
            specificServicePlaceholder: "e.g., Organic Tomato Seeds, Jersey Cow Milking",
            yourRating: "Your Rating",
            stars: (count) => count === 1 ? "star" : "stars",
            yourFeedback: "Your Feedback",
            feedbackPlaceholder: "Share your detailed experience with this service...",
            submitButton: "Submit Feedback",
            processing: "Processing...",
            thankYouMessage: "Thank You!",
            feedbackSubmitted: "Your feedback has been submitted successfully.",
            feedbackAnalyzing: "Your feedback is being analyzed",
            feedbackImprovement: "We'll use your input to improve our services",
            backToServices: "Back to Services",
            goBack: "Go Back",
        },
        sidebar: {
            adminPanel: "Admin Panel",
            coopPanel: "Cooperative Panel",
            dashboard: "Dashboard",
            insights: "Insights",
            services: "Services",
            cooperatives: "Cooperatives",
            farmers: "Farmers",
            communications: "Communications",
            visuals: "Visuals",
            recommendations: "Recommendations",
            reports: "Reports",
            addService: "Add Service",
            viewServices: "View Services",
            enableServices: "Enable Services",
            addCooperative: "Add Cooperative",
            editCooperative: "Edit Cooperative",
            viewCooperatives: "View Cooperatives",
            addFarmer: "Add Farmer",
            viewFarmers: "View Farmers",
            announcements: "Announcements",
        },
        landing: {
            welcomeTitle: "Welcome to Afran Qalloo FCU",
            subtitle: "Customer Satisfaction Analysis Platform",
            description:
                "Empowering better service delivery through real-time feedback and smart insights.",
        },
        landingCards: {
            coopSignup: "Sign Up as Cooperative",
            farmerSignup: "Sign Up as Farmer",
            coopLogin: "Login as Cooperative",
            farmerLogin: "Login as Farmer",
        },
        resetPassword: {
            title: "Reset Password",
            subtitle: "Enter your reset key and new password",
            resetKeyLabel: "Reset Key",
            newPasswordLabel: "New Password (min 6 characters)",
            confirmPasswordLabel: "Confirm Password",
            passwordLengthError: "Password must be at least 6 characters",
            passwordMismatchError: "Passwords do not match",
            successMessage: "Password reset successful!",
            genericError:
                "Failed to reset password. Please check your key and try again.",
            submitButton: "Reset Password",
            resettingText: "Resetting...",
        },
        farmerSignUp: {
            title: "Farmer Registration",
            subtitle: "Join our agricultural community",
            firstNameLabel: "First Name (min 2 characters)",
            firstNamePlaceholder: "Your name",
            firstNameError: "First name must be at least 2 characters",
            phoneNumberLabel: "Phone Number (09XXXXXXXX)",
            phoneNumberPlaceholder: "09XXXXXXXX",
            phoneNumberError: "Phone number must start with 09 and be 10 digits",
            registrationKeyLabel: "Registration Key",
            registrationKeyPlaceholder: "Your registration code",
            passwordLabel: "Password (min 6 characters)",
            passwordPlaceholder: "Create password",
            passwordLengthError: "Password must be at least 6 characters",
            confirmPasswordLabel: "Confirm Password",
            confirmPasswordPlaceholder: "Confirm password",
            passwordMismatchError: "Passwords do not match",
            successMessage: "Registration successful! Redirecting to login...",
            genericError:
                "Registration failed. Please check your details and try again.",
            submitButton: "Register Now",
            processingText: "Processing...",
            existingAccountText: "Already have an account?",
            signInText: "Sign in here",
        },
    },
    or: {
        common: {
            welcome: "Baga nagaan dhuftan",
            memberOf: "Miseensa",
            activeServices: "Tajaajilawwan hojiirra jiran",
            provideFeedback: "Yaada kennuu",
            viewDetails: "Details ilaaluu",
            signUp: "Galmaa'uu",
            login: "Seensa",
            logout: "Ba'i",
            joined: "Galmaa'ee",
            active: "Hojii irra jira",
            at: "irratti",
            posted: "Maxxanfame",
            home: "Mana",
            about: "Waa'ee",
            contact: "Qunnamtii",
            Phone_Number: "Lakkoofsa Bilbilaa",
            username: "Maqaa fayyadamaa",
            password: "Jecha Darbii",
            rememberMe: "Na yaadadhu",
            forgotPassword: "Jecha darbii dagattanii?",
            signingIn: "Seensa irra jira...",
            signIn: "Seensa",
            noAccount: "Akkaawuntii hin qabdu?",
            loginSuccess: "Seensa milkaa'e! Deebi'aa...",
            loginFailed: "Seensa hin dandeenye. Mirkanaa'aa keessan mirkaneessaa.",
        },
        farmer: {
            homeTitle: "Farmerii Dashboorii",
            feedbackTitle: "Tajaajilaa Yaada Kennuu",
            noServicesFound: "Tajaajila hojii irraa hin argamne",
            noServicesDescription: "Yeroo ammaatti tajaajila hojii irraa hin qabdu",
            exploreServices: "Tajaajilaa qoqqooduu",
            yourActiveServices: "Tajaajilawwan kee Hojii irra jiran",
            cooperativeAnnouncement: "Beekumsa Waldaa",
            upcomingMeeting: "Marii Waldaa dhufu",
            meetingDetails: "Marii Waldaa itti aanu yeroo",
            meetingLocation: "biraatti ofiisaa Waldaa",
            leadershipDiscussion: "hogganoonni qorannoo qonnaa haaraa mariyatu",
            loginSubtitle: "Hojii qonnaa keetii bulchuuf seenaa",
            phonePlaceholder: "Lakkoofsa bilbilaa kee galchaa",
            phoneValidation: "Lakkoofsa bilbilaa dhibbantoota 10 ta'e galchaa",
            passwordPlaceholder: "Jecha darbii kee galchaa",
            createAccount: "Farmerii haaraa uumuu",
        },
        admin: {
            homeTitle: "Admin Daashboordii",
            loginSubtitle: "Platformii fayyadamuuf seenaa",
            usernamePlaceholder: "Maqaa fayyadamaa kee galchaa",
            passwordPlaceholder: "Jecha darbii kee galchaa",
            joinAsCoop: "Waldaa Ta'uun Makamuuf",
        },
        cooperative: {
            homeTitle: "Waldaa Dashboorii",
            addFarmer: "Farmerii Haaraa Galmaa'uu",
            location: "Bakka",
            locationNotSpecified: "Bakka hin beekamne",
            cooperative: "Waldaa",
            totalFarmers: "Farmerota Waliigalaa",
            activeUsers: "Fayyadamaa Hojiirra Jiran",
            farmers: "farmeroota",
            noDescription: "Ibsa hin jiru",
            serviceID: "ID Tajaajilaa",
        },
        feedback: {
            noServiceSelected: "Tajaajilaa Filatamtu Hin Jiru",
            noServiceDescription: "Maaloo deebi'ii tajaajilaa yaada kennuuf filadhu.",
            feedbackFor: "Yaada",
            returnToServices: "Deebi'ii Tajaajilawwan",
            checkingEligibility: "Yaada kennuu dandeessuu keessan mirkaneessaa...",
            couldNotVerify: "Yaada kennuu dandeessuu keessan mirkaneessuu hindandeenye.",
            submitSuccess: "Yaada keessan gaheera!",
            submitFailed: "Yaada kennuu hin dandeenye.",
            specificService: "Tajaajilaa Addaa",
            specificServicePlaceholder: "fkn. Sanyii Toomaatii Orgaanikii, Sanyii Gaalaa Jeersii",
            yourRating: "Qixxeessuu Keessan",
            stars: (count) => count === 1 ? "urjii" : "urjiiwwan",
            yourFeedback: "Yaada Keessan",
            feedbackPlaceholder: "Odeeffannoo keessan tajaajila kana irratti nuuf kennaa...",
            submitButton: "Yaada Ergii",
            processing: "Hojii irra jira...",
            thankYouMessage: "Galatoomaa!",
            feedbackSubmitted: "Yaada keessan gaheera.",
            feedbackAnalyzing: "Yaada keessan qorannoo irra jira",
            feedbackImprovement: "Yaada keessan fayyadamuun tajaajila keenya fooyyessina",
            backToServices: "Deebi'ii Tajaajilawwan",
            goBack: "Deebi'i",
        },
        sidebar: {
            adminPanel: "Admin Paaneli",
            coopPanel: "Paaneelii Waldaa",
            dashboard: "Daashboordii",
            insights: "Hubannoo",
            services: "Tajaajilawwan",
            cooperatives: "Waldoota",
            farmers: "Farmeroota",
            communications: "Qunnamtii",
            visuals: "Mul'ifannoo",
            recommendations: "Gorsa",
            reports: "Ripoortii",
            addService: "Tajaajilaa Dabalachuu",
            viewServices: "Tajaajilawwan Ilaaluu",
            enableServices: "Tajaajilawwan Tumsuu",
            addCooperative: "Waldaa Dabalachuu",
            editCooperative: "Waldaa Gargaarsuu",
            viewCooperatives: "Waldoota Ilaaluu",
            addFarmer: "Farmerii Dabalachuu",
            viewFarmers: "Farmeroota Ilaaluu",
            announcements: "Beekumsa",
        },
        landing: {
            welcomeTitle: "Baga Nagaan Afran Qalloo FCU Geessan",
            subtitle: "Platformii Qorannoo Jaalatamummaa Makiinaa",
            description:
                "Tajaajila caalaa to'achuuf yaada yeroo dhugaa fi hubannoo garaan guddaa.",
        },
        landingCards: {
            coopSignup: "Waldaa Ta'uun Galmaa'uu",
            farmerSignup: "Farmerii Ta'uun Galmaa'uu",
            coopLogin: "Waldaa Ta'uun Seensuu",
            farmerLogin: "Farmerii Ta'uun Seensuu",
        },
        resetPassword: {
            title: "Jecha Darbii Sirrii Galuu",
            subtitle: "Lakkoofsa sirrii galuu fi jecha darbii haaraa galchaa",
            resetKeyLabel: "Lakkoofsa Sirrii Galuu",
            newPasswordLabel: "Jecha Darbii Haaraa (dhibbantoota 6 ol)",
            confirmPasswordLabel: "Jecha Darbii Mirkaneessuu",
            passwordLengthError: "Jecha darbiin dhibbantoota 6 ol ta'uu qaba",
            passwordMismatchError: "Jecha darbiin wal hin qabne",
            successMessage: "Jecha darbii sirrii galuu milkaa'e!",
            genericError:
                "Jecha darbii sirrii galuu hin dandeenye. Lakkoofsa sirrii galuu keessan mirkaneessaa.",
            submitButton: "Jecha Darbii Sirrii Galuu",
            resettingText: "Sirrii galuu...",
        },
        farmerSignUp: {
            title: "Farmerii Galmaa'uu",
            subtitle: "Waldaa qonnaa keessatti makamuuf",
            firstNameLabel: "Maqaa Duraa (dhibbantoota 2 ol)",
            firstNamePlaceholder: "Maqaa kee",
            firstNameError: "Maqaan duraan dhibbantoota 2 ol ta'uu qaba",
            phoneNumberLabel: "Lakkoofsa Bilbilaa (09XXXXXXXX)",
            phoneNumberPlaceholder: "09XXXXXXXX",
            phoneNumberError:
                "Lakkoofsi bilbilaa 09'n jalqaba ta'ee dhibbantoota 10 ta'uu qaba",
            registrationKeyLabel: "Lakkoofsa Galmaa'uu",
            registrationKeyPlaceholder: "Lakkoofsa galmaa'uu kee",
            passwordLabel: "Jecha Darbii (dhibbantoota 6 ol)",
            passwordPlaceholder: "Jecha darbii uumuu",
            passwordLengthError: "Jecha darbiin dhibbantoota 6 ol ta'uu qaba",
            confirmPasswordLabel: "Jecha Darbii Mirkaneessuu",
            confirmPasswordPlaceholder: "Jecha darbii mirkaneessuu",
            passwordMismatchError: "Jecha darbiin wal hin qabne",
            successMessage: "Galmaa'uu milkaa'e! Seensa irra deebi'aa...",
            genericError:
                "Galmaa'uu hin dandeenye. Odeeffannoo keessan mirkaneessaa.",
            submitButton: "Amma Galmaa'uu",
            processingText: "Hojiirra jira...",
            existingAccountText: "Akkaawuntii qabdu?",
            signInText: "Asii seenaa",
        },
    },
    am: {
        common: {
            welcome: "እንኳን ደህና መጡ",
            memberOf: "አባል",
            activeServices: "ንቁ አገልግሎቶች",
            provideFeedback: "ግብረ መልስ አስተያየት",
            viewDetails: "ዝርዝሮች ይመልከቱ",
            signUp: "ይመዝገቡ",
            login: "ግባ",
            logout: "ውጣ",
            joined: "ተጠቃሚ ሆኗል",
            active: "ንቁ",
            at: "በ",
            posted: "ተለጠፈ",
            home: "ዋና ገጽ",
            about: "ስለ እኛ",
            contact: "አግኙን",
            Phone_Number: "ስልክ ቁጥር",
            username: "የተጠቃሚ ስም",
            password: "የይለፍ ቃል",
            rememberMe: "አስታውሰኝ",
            forgotPassword: "የይለፍ ቃል ረሳኽው?",
            signingIn: "በመግባት ላይ...",
            signIn: "ግባ",
            noAccount: "መለያ የሎትም?",
            loginSuccess: "በተሳካ ሁኔታ ገብተዋል! ወደ መቀጠል...",
            loginFailed: "መግባት አልተቻለም። እባክዎ ማረጋገጫዎን ያረጋግጡ እና እንደገና ይሞክሩ።",
        },
        farmer: {
            homeTitle: "ገበሬ ዳሽቦርድ",
            feedbackTitle: "ስለ አገልግሎት አስተያየት አርድ",
            noServicesFound: "ምንም ንቁ አገልግሎቶች አልተገኙም",
            noServicesDescription: "በአሁኑ ጊዜ ምንም ንቁ አገልግሎቶች የሎትም",
            exploreServices: "አገልግሎቶችን ይመልከቱ",
            yourActiveServices: "የእርስዎ ንቁ አገልግሎቶች",
            cooperativeAnnouncement: "የማኅበር ማስታወቂያ",
            upcomingMeeting: "የሚመጣ ስብሰባ",
            meetingDetails: "የሚቀጥለው የመህበር ስብሰባ በ",
            meetingLocation: "በማኅበሩ ቢሮ",
            leadershipDiscussion: "ሊዳርሽፕ አዳዲስ የሰርቻ ቴክኖሎጂዎችን ይዘረዝራል",
            loginSubtitle: "የእርሻ እንቅስቃሴዎን ለመቆጣጠር ይግቡ",
            phonePlaceholder: "ስልክ ቁጥርዎን ያስገቡ",
            phoneValidation: "እባክዎ 10-አሃዝ ስልክ ቁጥር ያስገቡ",
            passwordPlaceholder: "የይለፍ ቃልዎን ያስገቡ",
            createAccount: "አዲስ ገበሬ መለያ ይፍጠሩ",
        },
        admin: {
            homeTitle: "አስተዳዳሪ ዳሽቦርድ",
            loginSubtitle: "መድረኩን ለመጠቀም ይግቡ",
            usernamePlaceholder: "የተጠቃሚ ስምዎን ያስገቡ",
            passwordPlaceholder: "የይለፍ ቃልዎን ያስገቡ",
            joinAsCoop: "እንደ ማኅበር ይቀላቀሉ",
        },
        cooperative: {
            homeTitle: "ማኅበረ ዳሽቦርድ",
            addFarmer: "አዲስ ገበሬ ያስመዝግቡ",
            location: "ቦታ",
            locationNotSpecified: "ቦታ አልተገለጸም",
            cooperative: "ማኅበረ",
            totalFarmers: "ጠቅላላ ገበሬዎች",
            activeUsers: "ንቁ ተጠቃሚዎች",
            farmers: "ገበሬዎች",
            noDescription: "ምንም መግለጫ የለም",
            serviceID: "የአገልግሎት መታወቂያ",
        },
        feedback: {
            noServiceSelected: "አገልግሎት አልተመረጠም",
            noServiceDescription: "እባክዎ ወደ ኋላ ተመልሰው ለመግለጫ አገልግሎት ይምረጡ።",
            feedbackFor: "ግብረ መልስ ለ",
            returnToServices: "ወደ አገልግሎቶች ተመለስ",
            checkingEligibility: "የግብረ መልስ ለመስጠት እስለጣሽ በመፈተሽ ላይ...",
            couldNotVerify: "የግብረ መልስ ለመስጠት የሚችሉ መሆንዎን ማረጋገጥ አልተቻለም።",
            submitSuccess: "ግብረ መልስዎ በተሳካ ሁኔታ ቀርቧል!",
            submitFailed: "ግብረ መልስ ለመስጠት አልተቻለም።",
            specificService: "የአገልግሎት አይነት",
            specificServicePlaceholder: "ለምሳሌ፡ ኦርጋኒክ ቲማቲም ዘሮች፣ ጀርሲ ላም አጥባቂ",
            yourRating: "ደረጃ መስጠት",
            stars: (count) => count === 1 ? "ኮከብ" : "ኮከቦች",
            yourFeedback: "የእርስዎ ግብረ መልስ",
            feedbackPlaceholder: "በዚህ አገልግሎት ላይ ያለዎትን ልምድ ያካፍሉን...",
            submitButton: "ግብረ መልስ ላክ",
            processing: "በማቀናበር ላይ...",
            thankYouMessage: "አመሰግናለሁ!",
            feedbackSubmitted: "ግብረ መልስዎ በተሳካ ሁኔታ ቀርቧል።",
            feedbackAnalyzing: "ግብረ መልስዎ በመተንተን ላይ ነው",
            feedbackImprovement: "ግብረ መልስዎን በመጠቀም አገልግሎታችንን እናሻሽላለን",
            backToServices: "ወደ አገልግሎቶች ተመለስ",
            goBack: "ወደ ኋላ ተመለስ",
        },
        sidebar: {
            adminPanel: "የአስተዳደር ፓነል",
            coopPanel: "የመህበር ፓነል",
            dashboard: "ዳሽቦርድ",
            insights: "እይታዎች",
            services: "አገልግሎቶች",
            cooperatives: "መህበራት",
            farmers: "ገበሬዎች",
            communications: "ግንኙነት",
            visuals: "ምስላዊ",
            recommendations: "ምክረ ሃሳቦች",
            reports: "ሪፖርቶች",
            addService: "አገልግሎት ያክሉ",
            viewServices: "አገልግሎቶችን ይመልከቱ",
            enableServices: "አገልግሎቶችን ያንቁ",
            addCooperative: "መህበር ያክሉ",
            editCooperative: "መህበር ያርትዑ",
            viewCooperatives: "መህበራትን ይመልከቱ",
            addFarmer: "ገበሬ ያክሉ",
            viewFarmers: "ገበሬዎችን ይመልከቱ",
            announcements: "ማስታወቂያዎች",
        },
        landing: {
            welcomeTitle: "ወደ አፍራን ቃሉ እንኳን በደህና መጡ",
            subtitle: "የደንበኛ እርካታ ትንታኔ መድረክ",
            description: "በቅጽበታዊ ግብረ መልስ እና ዘመናዊ ትንታኔ የተሻለ አገልግሎት ለመስጠት እያበረታታ ።",
        },
        landingCards: {
            coopSignup: "እንደ ማህበር ይመዝገቡ",
            farmerSignup: "እንደ ገበሬ ይመዝገቡ",
            coopLogin: "እንደ ማህበር ይግቡ",
            farmerLogin: "እንደ ገበሬ ይግቡ",
        },
        resetPassword: {
            title: "የይለፍ ቃል ዳግም ያቀናብሩ",
            subtitle: "የሚያስጀምሩትን ቁልፍ እና አዲስ የይለፍ ቃል ያስገቡ",
            resetKeyLabel: "የሚያስጀምሩትን ቁልፍ",
            newPasswordLabel: "አዲስ የይለፍ ቃል (ቢያንስ 6 ቁምፊዎች)",
            confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
            passwordLengthError: "የይለፍ ቃሉ ቢያንስ 6 ቁምፊዎች ሊኖሩት ይገባል",
            passwordMismatchError: "የይለፍ ቃላቶች አንድ አይነት አይደሉም",
            successMessage: "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል!",
            genericError:
                "የይለፍ ቃል ለመቀየር አልተቻለም። እባክዎ የሚያስጀምሩትን ቁልፍ ያረጋግጡ እና እንደገና ይሞክሩ።",
            submitButton: "የይለፍ ቃል ዳግም ያቀናብሩ",
            resettingText: "በመቀየር ላይ...",
        },
        farmerSignUp: {
            title: "የገበሬ ምዝገባ",
            subtitle: "የግብርና ማህበረሰባችን ይቀላቀሉ",
            firstNameLabel: "የመጀመሪያ ስም (ቢያንስ 2 ፊደላት)",
            firstNamePlaceholder: "ስምህ",
            firstNameError: "የመጀመሪያ ስም ቢያንስ 2 ፊደላት ሊኖሩት ይገባል",
            phoneNumberLabel: "ስልክ ቁጥር (09XXXXXXXX)",
            phoneNumberPlaceholder: "09XXXXXXXX",
            phoneNumberError: "ስልክ ቁጥር በ09 መጀመር እና 10 አሃዞች ሊኖሩት ይገባል",
            registrationKeyLabel: "የምዝገባ ቁልፍ",
            registrationKeyPlaceholder: "የምዝገባ ቁልፍህ",
            passwordLabel: "የይለፍ ቃል (ቢያንስ 6 ፊደላት)",
            passwordPlaceholder: "የይለፍ ቃል ይፍጠሩ",
            passwordLengthError: "የይለፍ ቃል ቢያንስ 6 ፊደላት ሊኖሩት ይገባል",
            confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
            confirmPasswordPlaceholder: "የይለፍ ቃል ያረጋግጡ",
            passwordMismatchError: "የይለፍ ቃላቶች አንድ አይነት አይደሉም",
            successMessage: "ምዝገባ በተሳካ ሁኔታ ተጠናቅቋል! ወደ መግቢያ በመሄድ ላይ...",
            genericError: "ምዝገባ አልተሳካም። እባክዎ ዝርዝሮችዎን ያረጋግጡ እና እንደገና ይሞክሩ።",
            submitButton: "አሁን ይመዝገቡ",
            processingText: "በሂደት ላይ...",
            existingAccountText: "አካውንት አለህ?",
            signInText: "እዚህ ይግቡ",
        },
    },
};

// Create context
export const LanguageContext = createContext();

// Language Provider Component
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState("en");

    // Load language preference from localStorage
    useEffect(() => {
        const savedLanguage = localStorage.getItem("appLanguage");
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);

    // Save language preference when it changes
    useEffect(() => {
        localStorage.setItem("appLanguage", language);
    }, [language]);

    // Translation function with nested key support
    const translate = (key) => {
        const keys = key.split(".");
        let result = translations[language];

        for (const k of keys) {
            result = result?.[k];
            if (result === undefined) {
                console.warn(`Missing translation for key: ${key}`);
                return key; // Return key if translation not found
            }
        }

        return result || key;
    };

    return (
        <LanguageContext.Provider
            value={{
                language,
                setLanguage,
                translate,
                availableLanguages: Object.keys(translations),
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

// Custom hook for easier usage
export const useLanguage = () => {
    const context = React.useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
