# Generated by Django 5.1.7 on 2025-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message_in_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
