# Generated by Django 5.1.7 on 2025-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_message_in_english_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='specific_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='summarized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
