# Generated by Django 5.1.7 on 2025-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_specific_service_feedback_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_or',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
