# Generated by Django 5.1.7 on 2025-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_service_name_am_service_name_or'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='responses_remaining',
            field=models.IntegerField(default=1),
        ),
    ]
